.github/CODEOWNERS
.github/workflows/node.js.yml
.gitignore
package.json

* github action CI 추가
* prettier, tsc 스크립트 추가

Feature: github action CI 추가

---

src/themes/Color.stories.tsx

- colorList 쪽에 object entries 적용했는데 이거 하시려던거 맞나요??
https://github.com/depromeet/sulsul-FE/pull/8/files#r857139510

refactor: ♻️ ColorList에 object entries 적용

---

src/components/BeerDetail/BeerDetail.tsx
src/components/commons/Button/Button.stories.tsx
src/components/commons/Button/Button.tsx
src/themes/Color.stories.tsx
src/themes/index.ts
src/themes/types.ts

- theme color 추가 (grey, primaryOpacity, secondaryOpacity)
- disabled 및 default 버튼 스타일 변경
- line 타입 추가 (primary-line, secondary-line)
- 버튼에 count 표시 기능 추가
[스토리북 링크](https://62472322b43dfc003a759108-qebwctewff.chromatic.com/?path=/story/commons-button--primary)

refactor: ♻️ common button 변경된 디자인 적용

---

.storybook/preview.js
src/components/SwiperLayout/SwiperLayout.stories.tsx
src/components/SwiperLayout/SwiperLayout.tsx
src/components/SwiperLayout/index.ts

- storybook 전체 레이아웃 height 100% 로 변경
- SwiperLayout 컴포넌트 구현
- 우선 form에서 swiper 기능을 포함한 layout으로 사용하려고 구현함
[스토리북 링크](https://62472322b43dfc003a759108-qqbxmedxfg.chromatic.com/?path=/story/components-swiperlayout--%EC%8A%A4%EC%99%80%EC%9D%B4%ED%8D%BC-%EB%A0%88%EC%9D%B4%EC%95%84%EC%9B%83)
- storybook에서 테스트 할 수있도록 dummypage랑 페이지 이동 버튼 구현해놓았슴다

feat: ✨ SwiperLayout 컴포넌트 구현

---

src/components/formFields/EmojiRadioField/EmojiRadioField.stories.tsx
src/components/formFields/EmojiRadioField/EmojiTransitionViewer.tsx

- emoji transition viewer 애니메이션 수정
- 이번껀 진짜 쫌 이뻐요

refactor:♻️ emoji transition viewer 애니메이션 수정

---

src/containers/recordStepContainers/RecordSecondStepContainer/RecordSecondStepContainer.stories.tsx
src/containers/recordStepContainers/RecordSecondStepContainer/RecordSecondStepContainer.tsx
src/containers/recordStepContainers/RecordSecondStepContainer/index.ts

- Record 기록 두번째 페이지 section 구현
- 이것도 첫페이지 처럼 section 부분만 넣었습니다

feat: ✨ Record 기록 두번째 페이지 section 구현

---

src/components/formFields/SelectField/SelectField.stories.tsx
src/components/formFields/SelectField/SelectField.tsx
src/components/formFields/SelectField/index.ts
src/components/formFields/TextAreaField/TextAreaField.tsx
src/containers/recordStepContainers/RecordSecondStepContainer/RecordSecondStepContainer.tsx
src/containers/recordStepContainers/RecordThirdStepContainer/RecordThirdStepContainer.stories.tsx
src/containers/recordStepContainers/RecordThirdStepContainer/RecordThirdStepContainer.tsx
src/containers/recordStepContainers/RecordThirdStepContainer/index.ts

- Record 기록 두번째 페이지 section 구현
- TextAreaField props 개선
- Record 2page 문구 수정
- SelectField 구현 (기존 SelectField 활용)
- 세번째 페이지^^

feat: ✨ Record 기록 세번째 페이지 section 구현

---

package.json
src/components/BeerTicket/BeerTicket.stories.tsx
src/components/BeerTicket/BeerTicket.tsx
src/components/BeerTicket/BeerTicketField.tsx
src/components/BeerTicket/BeerTicketFlight.tsx
src/components/BeerTicket/index.ts
src/components/commons/Icon/svg/index.tsx
src/components/formFields/EmojiRadioField/EmojiRadioGroup.tsx
src/constants/Reviews.ts
yarn.lock

- date-fns 설치
- BeerTicket 컴포넌트 구현
- [스토리북 링크](https://62829ab0a36680004a2132e7-zcfcgpefni.chromatic.com/?path=/story/components-beerticket--%ED%8B%B0%EC%BC%93)
홈화면에서 사용되는 부분들은 나중에 pr에서 분기할게요^^ 코드 길어질것 같아서^^

feature: BeerTicket 컴포넌트 구현

---

package.json
src/containers/BeerDetailContainer/BeerDetailContainer.stories.tsx
src/containers/BeerDetailContainer/BeerDetailContainer.tsx
src/pages/beer/[id].tsx
src/utils/share.ts
src/utils/toast.ts
yarn.lock

참고 : [share api ](https://developer.mozilla.org/ko/docs/Web/API/Navigator/share)
생각보다 많은 브라우저에서 지원하더라구요!
이런식으로 title, text, url 넣어서 공유할 수 있습니다!
```
share({
title: `BEER:AiR`,
text: `맥주 상세정보 페이지입니다.`,
url: window.location.href,
})
```

feat: :sparkles: 공유하기 기능 추가

---

.eslintrc
src/apis/record/create-record.ts
src/apis/record/index.ts
src/apis/record/record.ts
src/components/BeerTicket/BeerTicket.stories.tsx
src/components/BeerTicket/BeerTicket.tsx
src/constants/Record.ts
src/containers/CompletedRecordContainer/CompletedRecordContainer.stories.tsx
src/containers/CompletedRecordContainer/CompletedRecordContainer.tsx
src/containers/CompletedRecordContainer/index.ts

- record 관련 타입 정의
- 기록 생성 완료 페이지 구현
- api는 나중에 적용할게요

feat: ✨ 기록 생성 완료 페이지 구현

---

src/components/RecordListItem/RecordListItem.stories.tsx
src/components/RecordListItem/RecordListItem.tsx
src/components/RecordListItem/index.ts
src/constants/Record.ts

- RecordListItem 컴포넌트 구현
- 리스트를 만들때 위아래로 연결되는 띠 구현 예정입니다

feat: ✨RecordListItem 컴포넌트 구현

---

src/apis/beer.ts
src/apis/index.ts
src/apis/upload/image-upload.ts
src/apis/upload/index.ts
src/components/formFields/ImageUploadField/ImageUploadField.tsx
src/constants/Beers.ts
src/containers/CreateRecordContainer/RecordThirdStepContainer/RecordThirdStepContainer.tsx

- 이미지 upload api react-query 사용해서 연결
- Date형식 number도 지원하도록 수정

feat: ✨이미지 업로드 api 연결

---

src/components/commons/Icon/Icon.tsx

- 컴포넌트 내부에서 styled component 생성할 때 에러가 발생해 다음과 같이 css props 주입하는 방식으로 변경했슴다
https://github.com/depromeet/sulsul-FE/issues/87#issuecomment-1146514454

fix: react component styled generator 구조 변경

---

deploy.sh
pm2.yml

- pm2 config 작성
- deploy shell script 작성
- http://43.200.72.216:3000
- 도메인 연결중이라 연결되면 https 작업할게요

deploy: 🚀 배포 명령 스크립트 작성

---

src/components/BottomNavigation/BottomNavigation.tsx
src/components/RecordList/RecordList.tsx
src/components/RecordListItem/RecordListItem.tsx
src/containers/CompletedRecordContainer/index.ts
src/containers/CreateRecordContainer/RecordThirdStepContainer/RecordThirdStepContainer.tsx
src/containers/RecordTicketContainer/RecordTicketContainer.stories.tsx
src/containers/RecordTicketContainer/RecordTicketContainer.tsx
src/containers/RecordTicketContainer/index.ts
src/containers/RecordsContainer/RecordsContainer.tsx
src/pages/record/ticket/[id].tsx

- my records 페이지에서 record ticket 상세페이지 연결!
- 기존 recordTIcketContainer 를 재사용하기 위해 리팩터링
^^

feat: ✨ my records 페이지에서 record ticket 상세페이지 연결!

---

src/components/Header/Header.tsx
src/containers/BeerDetailContainer/BeerDetailContainer.tsx

feat: :sparkles: 맥주 상세페이지 스크롤 인터랙션 구현

---

src/containers/BeerDetailContainer/BeerDetailContainer.tsx
src/pages/_app.tsx

feat: :sparkles: og title, description, image 설정, 맥주 상세정보 페이지 share 시 나오는 description 수정

---

src/components/BeerListPageHeader/BeerListPageHeader.tsx
src/components/search/SearchList/SearchList.tsx
src/containers/SearchContainer/SearchContainer.stories.tsx
src/containers/SearchContainer/SearchContainer.tsx
src/containers/SearchContainer/SearchInput.tsx
src/containers/SearchContainer/index.ts
src/pages/search.ts

- search 페이지 구현
- search 페이지와 각 페이지 연결
^^

feat: 🍻 Search 페이지 구현

---

.gitignore
next.config.js
package.json
sentry.client.config.js
sentry.properties
sentry.server.config.js
src/pages/_error.js
yarn.lock

chore: 🚧sentry 설정 추가

---

src/apis/index.ts
src/apis/request-beer/create-request-beer.ts
src/apis/request-beer/index.ts
src/apis/request-beer/request-beer.ts
src/apis/upload/image-upload.ts
src/apis/upload/images-upload.ts
src/apis/upload/index.ts
src/components/EntityForm/EntityForm.tsx
src/components/commons/FormSubmitButton/FormSubmitButton.tsx
src/components/formFields/TextField/TextField.stories.tsx
src/components/formFields/TextField/TextField.tsx
src/components/formFields/TextField/index.ts
src/components/layouts/BeerRequestLayout/BeerRequestLayout.tsx
src/containers/BeerRequestContainer/BeerRequestContainer.stories.tsx
src/containers/BeerRequestContainer/BeerRequestContainer.tsx
src/containers/BeerRequestContainer/index.ts
src/pages/beer/request/index.tsx

feat: 미등록 맥주 요청 페이지 추가

---

package.json
src/pages/_app.tsx
yarn.lock

- nextjs prod 환경에서 server side에서 axios 요청 시 입력한 cookie가 유실되는 현상 발생
- nextjs 버전 변경으로 인한 수정
- 각 default cookie를 공유하지 않도록 매 요청마다 cookie 초기화
^^...ㅜㅜ

fix: :lipstick: axios cookie 버그로 인한 nextjs 버전 업데이트

---

src/apis/beer.ts
src/apis/continent.ts
src/apis/country/get-countries.ts
src/apis/country/get-recently-visited-county.ts
src/apis/profile.ts
src/apis/record/create-record.ts
src/apis/record/get-my-records.ts
src/apis/record/get-record.ts
src/apis/record/record.ts
src/apis/request-beer/create-request-beer.ts
src/apis/upload/image-upload.ts
src/apis/upload/images-upload.ts
src/apis/user/delete-user.ts
src/apis/user/get-user.ts
src/apis/user/update-user.ts
src/configs/axios.ts
src/pages/_app.tsx

- nextjs 버전 문제인지 알았는데 axios client를 만들어서 사용중이어서 defulat config가 정상적으로 작동하지 않는 문제였음
- 기존 instance를 만드는 방식 대신 default config를 initialize 하는 방식으로 변경

fix: 💄 axios cookie 버그로 인한 default config 방식 수정

---

src/components/BeerTicketTitle/BeerTicketTitle.tsx
src/components/RecordListItem/RecordListItem.tsx

feat: :sparkles: 업로드한 이미지 흑백처리

---

src/components/search/SearchItem/SearchItem.tsx

- 최근 검색어 클릭 시 검색기능 적용^^
- https://github.com/depromeet/sulsul-FE/issues/125

feat: ✨최근 검색어 클릭 시 검색기능 적용

---

src/assets/airplane_loading.svg
src/containers/RecordsContainer/EmptyRecords.tsx
src/containers/RecordsContainer/RecordsContainer.tsx

feat: ✨records 비어있을 때 empty 표시 적용

---

src/components/ErrorBoundary/ErrorBoundary.tsx
src/components/ErrorBoundary/ErrorPage.stories.tsx
src/components/ErrorBoundary/ErrorPage.tsx
src/components/ErrorBoundary/index.ts
src/pages/_app.tsx

feat: :sparkles: ErrorBoundary 컴포넌트 구현

---

src/containers/RecordTicketContainer/CreateImage.tsx

fix: :bug: 저장하기 버튼 두번째 이상 눌렀을 때 저장 모달이 발생하지 않는 이슈 수정

---

src/components/BeerTicket/BeerTicket.tsx

fix: :bug: 티켓 등록할 때 긴 텍스트 UI로 수정

---

src/queries/useGetRecordsByBeer.ts

fix: :bug: 맥주 상세페이지 댓글 무한스크롤 getNextPagePararm 수정

---

src/components/BottomFloatingButtonArea/BottomFloatingButtonArea.tsx

fix: :bug: BottomFloatingButtonArea로 인한 컨텐츠 가림 문제 수정

---

src/components/AirPort/AirPort.tsx
src/components/ReviewList/ReviewList.tsx
src/components/beerItem/BeerGridItem/BeerGridItem.tsx
src/containers/BeerDetailContainer/BeerDetailContainer.tsx

fix: 자잘한 ui 버그 수정

---

src/components/BottomFloatingButtonArea/BottomFloatingButtonArea.tsx
src/components/BottomFloatingButtonArea/index.ts
src/components/formFields/EmojiRadioField/EmojiRadioGroup.tsx
src/components/layouts/SwiperLayout/SwiperLayout.tsx
src/containers/UpsertRecordContainer/RecordFirstStepContainer/RecordFirstStepContainer.tsx
src/containers/UpsertRecordContainer/RecordSecondStepContainer/RecordSecondStepContainer.tsx
src/containers/UpsertRecordContainer/RecordThirdStepContainer/RecordThirdStepContainer.tsx
src/containers/UpsertRecordContainer/UpsertRecordContainer.tsx

fix: ui 버그 일괄 수정

---

src/utils/share.ts

https://github.com/depromeet/sulsul-FE/issues/181

fix: :bug: 링크 공유 로직 변경

---

src/containers/SignUpContainer/SignUpContainer.tsx

- maxLength 체크 시 상태값을 사용하지 않고 event 값 사용
- https://github.com/depromeet/sulsul-FE/issues/184
-

fix: :bug: maxLength 체크 시 상태값을 사용하지 않고 event 값 사용

---

README.md

리드미 초안을 작성했습니다
다른 레포들 참고해서 작성했고, 우선 서비스 소개 위주로 작성을 헀어요
추가적으로 아래 정보들으르 작성한 레포들도 있더라구요
- 앱 배포링크 (플레이스토어, 앱스토어)
- FE 레포 관련
- 디렉토리 구조
- 웹사이트 성능 측정, 번들사이즈
- 프로젝트 참여자 역할 (어떤파트를 담당해서 개발했는지)
- 버그 및 새로운 기능 제안 링크 (깃허브 이슈) 
이 부분은 저희끼리 협의해서 추가적으로 작성하면 될 것 같습니다!

docs: :memo: README.md 초안 작성

---

src/containers/HomeContainer/HomeSearchBar.tsx

fix: :bug: HomeSearchBar align-items: center css 추가

---

src/components/Emoji/Emoji.tsx

이모지를 채우고 싶은 마음이 들게 하려는 의도였으나, 미완성된 UI라고 생각하는 사람이 많은 것 같아서 제거
훨씬 낫나요?
https://github.com/depromeet/sulsul-FE/issues/223

fix: 💄 빈 이모지 제거

---

src/containers/UpsertRecordContainer/RecordThirdStepContainer/RecordThirdStepContainer.tsx

https://github.com/depromeet/sulsul-FE/issues/215
https://github.com/depromeet/sulsul-FE/issues/214

fix: :beers: 공개여부 true default로 변경, 다음 -> 완료 수정

---

README.md

docs: :beers: awsome android 다운로드 버튼 추가^^

---

package.json
src/containers/RecordTicketContainer/RecordTicketContainer.tsx
yarn.lock

feat: :lipstick: 기록 완료 페이지 react-rewards 적용
